apiVersion: v1
kind: Pod
metadata:
  name: config-pod
spec:
  containers:
    - name: felix-web
      image: registry.access.redhat.com/ubi9/httpd-24:9.7
      ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        - name: https
          containerPort: 8443

    - name: floris-db
      image: registry.fedoraproject.org/f32/mysql
      ports:
        - name: dbport
          containerPort: 3306
      env:
        - name: MYSQL_USER
          value: marius
        - name: MYSQL_DATABASE
          value: aristo

        - name: MYSQL_PASSWORD
          value: mypa55
        - name: MYSQL_ROOT_PASSWORD
          value: r00tpa55
