---
apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: cm-redhat
data:
  database: aristo
  user: marius
---
apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  name: sec-redhat
data:
  password: bXlwYTU1
  root_password: cjAwdHBhNTU=
 
---
apiVersion: v1
kind: Pod
metadata:
  name: floris
spec:
  containers:
    - name: felix-web
      image: registry.access.redhat.com/ubi9/httpd-24:9.7
      ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        - name: https
          containerPort: 8443

    - name: floris-db
      image: registry.fedoraproject.org/f32/mysql
      ports:
        - name: dbport
          containerPort: 3306
      env:
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              name: cm-redhat
              key: user
            
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: cm-redhat
              key: database

        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sec-redhat
              key: password

        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sec-redhat
              key: root_password

# oc create cm cm-redhat --from-literal=user=marius --from-literal=database=aristo --dry-run=client -o yaml
# oc create secret generic sec-redhat --from-literal=password=mypa55 --from-literal=root_password=r00tpa55  --dry-run=client -o yaml >> config-app.yml
